version: '3'

services:

  # proxies requests
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - cat-generator
      - cat-namer
      - cat-imager
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # vue application
  cat-generator:
    image: cat-generator
    container_name: cat-generator
    build:
      context: ./cat_generator
    depends_on:
      - cat-namer
      - cat-imager
    ports:
      - 8080:80
    restart: on-failure

  # cat namer
  cat-namer:
    image: cat-namer
    container_name: cat-namer
    build:
      context: ./cat_namer
    ports:
      - 5001:5001
    restart: on-failure

  # cat image
  cat-imager:
    image: cat-imager
    container_name: cat-imager
    build:
      context: ./cat_imager
    ports:
      - 5002:5002
    restart: on-failure
